root: true
extends:
  - react-app
  - react-app/jest

rules:
  import/newline-after-import: error
  import/no-duplicates: error
  import/no-nodejs-modules: error
  import/order:
    - error
    - groups: [[builtin, external], [parent, sibling, index]]
      newlines-between: always
      alphabetize: { order: asc, caseInsensitive: true }

  no-console:
    - error
    - allow: [error, warn]

  object-shorthand: error
  prefer-const: error

  react/jsx-no-useless-fragment: error
  react/self-closing-comp:
    - error
    - component: true
      html: true

  sort-imports:
    - error
    - ignoreCase: false
      ignoreDeclarationSort: true
