root: true
extends:
  - react-app
  - react-app/jest

rules:
  import/newline-after-import: warn
  import/no-duplicates: warn
  import/no-nodejs-modules: warn
  import/order:
    - warn
    - groups: [[builtin, external], [parent, sibling, index]]
      newlines-between: always
      alphabetize: { order: asc, caseInsensitive: true }

  no-console:
    - warn
    - allow: [error, warn]

  object-shorthand: warn
  prefer-const: warn

  react/jsx-no-useless-fragment: warn
  react/self-closing-comp:
    - warn
    - component: true
      html: true

  sort-imports:
    - warn
    - ignoreCase: false
      ignoreDeclarationSort: true
